<?php

use Illuminate\Database\Seeder;

class TrackingFilterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tracking_filter')->insert([ 'doc_type' => 'SAL', 'description' => 1, 'amount' => 1, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 1, 'payee' => 0, 'item' => 0, 'dv_no' => 1,'ors_no' => 1,'fund_source_budget' => 1 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'TEV', 'description' => 1, 'amount' => 1, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 1, 'payee' => 0, 'item' => 0, 'dv_no' => 1,'ors_no' => 1,'fund_source_budget' => 1 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'BILLS', 'description' => 1, 'amount' => 1, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 1,'ors_no' => 1,'fund_source_budget' => 1 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'SUPPLIER', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'INFRA', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'INCOMING', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'OUTGOING', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'SERVICE', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'SALN', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'PLANS', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'ROUTE', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'MEMO', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'ISO', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'APPOINTMENT', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'RESOLUTION', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'WORKSHEET', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'JUST_LETTER', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'CERT', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'CERT_APPEARANCE', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'CERT_EMPLOYMENT', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'CERT_CLEARANCE', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'OFFICE_ORDER', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'DTR', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'CDO', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'OT', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'TIME_OFF', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'PO', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'PRC', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'PRR', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'REPORT', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
        DB::table('tracking_filter')->insert([ 'doc_type' => 'GENERAL', 'description' => 1, 'amount' => 0, 'pr_no' => 0, 'po_no' => 0, 'purpose' => 0, 'source_fund' => 0, 'requested_by' => 0, 'route_to' => 0, 'route_from' => 0, 'supplier' => 0, 'event_date' => 0, 'event_location' => 0, 'event_participant' => 0, 'cdo_applicant' => 0, 'cdo_day' => 0, 'event_daterange' => 0, 'payee' => 0, 'item' => 0, 'dv_no' => 0 ]);
    }
}
